<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up()
    {
        Schema::create('report_cards', function (Blueprint $table) {
            $table->id();
            $table->foreignId('student_id')->constrained()->onDelete('cascade');
            $table->foreignId('class_id')->constrained()->onDelete('cascade');
            $table->foreignId('class_arm_id')->constrained()->onDelete('cascade');
            $table->foreignId('term_id')->constrained()->onDelete('cascade');
            $table->foreignId('academic_year_id')->constrained()->onDelete('cascade');
            
            // Summary
            $table->decimal('total_score', 8, 2)->nullable();
            $table->decimal('average_score', 5, 2)->nullable();
            $table->integer('position')->nullable();
            $table->integer('total_students')->nullable();
            $table->decimal('grade_point_average', 5, 2)->nullable(); // GPA
            
            // Results
            $table->integer('total_subjects')->default(0);
            $table->integer('subjects_passed')->default(0);
            $table->integer('subjects_failed')->default(0);
            
            // Promotion
            $table->enum('promotion_status', ['promoted', 'demoted', 'repeated', 'pending'])->default('pending');
            $table->text('principal_remarks')->nullable();
            $table->text('class_teacher_remarks')->nullable();
            
            // Status
            $table->enum('status', ['draft', 'published', 'archived'])->default('draft');
            
            // Generated by
            $table->foreignId('generated_by')->constrained('users');
            $table->timestamp('published_at')->nullable();
            
            $table->timestamps();
            
            // Unique constraint
            $table->unique(['student_id', 'term_id', 'academic_year_id'], 'unique_report_card');
        });
    }

    public function down()
    {
        Schema::dropIfExists('report_cards');
    }
};